---
include:
  - board: eyelash_sofle_right
    shield: nice_view_adapter nice_epaper
    artifact-name: eyelash_sofle_right

  - board: eyelash_sofle_left
    shield: nice_view_adapter nice_view_custom
    artifact-name: eyelash_sofle_left

  - board: eyelash_sofle_right
    shield: settings_reset
    artifact-name: eyelash_reset

  # - board: eyelash_sofle_left
  #   shield: nice_view
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #   artifact-name: eyelash_sofle_studio_left
